#!/bin/bash
sudo apt-get install virtualenv

rm -r ./venv
virtualenv -p python3.8 ./venv
source ./venv/bin/activate

./venv/bin/pip install --requirement=./requirements.txt

python manage.py makemigrations
python manage.py migrate
python manage.py runserver
